config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root 'tops#index'

  resources :notes do
    resource :reference, only: [] do
      post 'increment_clicks', on: :member
    end
  end

  resources :prompts, only: [:new, :create, :show, :edit, :update, :destroy] do
    resource :reference, only: [] do
      post 'increment_clicks', on: :member
    end
    resources :notes, only: [:new, :create]
  end

  resources :searches, only: [] do
    collection do
      get 'tags'
      get 'results'
    end
  end

  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get 'basic_info', to: 'users#basic_info'
      get 'notes_info', to: 'users#notes_info'
      get 'prompts_info', to: 'users#prompts_info'
    end
  end

  resources :administrators, only: [:index] do
    member do
      patch :update_owner
      delete :destroy_user
    end
  end
end

app/views/shared/_basic_info.html.erb
<div class="basic-info-section">
  <div class="custom-field">
    <h3>基本情報</h3>
    <% if current_user == @user %>
      <div class="button-group">
        <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
  <div>
    <strong>NickName:</strong> <%= @user.nickname %>
  </div>
  <div>
    <strong>Email:</strong> <%= @user.email %>
  </div>
  <div>
    <strong>Group:</strong> <%= @user.group.name %>
  </div>
  <div>
    <strong>Profile:</strong> <%= simple_format(@user.profile) %>
  </div>
  <div class="content-info container mt-4">
    <div class="row mt-4">
      <div class="col-md-6">
        <h4>Note Information</h4>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Category</th>
              <th>Total</th>
              <th>Public</th>
              <th>Private</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Notes</td>
              <td><%= @note_information[:total] %></td>
              <td><%= @note_information[:public] %></td>
              <td><%= @note_information[:private] %></td>
            </tr>
            <tr>
              <td>Reference Clicks</td>
              <td><%= @note_information[:total_reference_clicks] %></td>
              <td></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="col-md-6">
        <h4>Prompt Information</h4>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Category</th>
              <th>Total</th>
              <th>Public</th>
              <th>Private</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Prompts</td>
              <td><%= @prompt_information[:total] %></td>
              <td><%= @prompt_information[:public] %></td>
              <td><%= @prompt_information[:private] %></td>
            </tr>
            <tr>
              <td>Reference Clicks</td>
              <td><%= @prompt_information[:total_reference_clicks] %></td>
              <td></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/shared/_category_note_list.html.erb
<% @notes_by_category.each do |category, notes| %>
  <li class="mb-1">
    <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0" data-bs-toggle="collapse" data-bs-target="#note-category-<%= category.id %>-collapse" aria-expanded="false">
      <%= category.name %>
    </button>
    <div class="collapse" id="note-category-<%= category.id %>-collapse">
      <ul class="btn-toggle-nav list-unstyled small">
        <% notes.each do |note| %>
          <li>
            <%= link_to note.title, note_path(note), class: 'link-body-emphasis text-decoration-none' %>
          </li>
        <% end %>
      </ul>
    </div>
  </li>
<% end %>

app/views/shared/_category_prompt_list.html.erb
<% @prompts_by_category.each do |category, prompts| %>
  <li class="mb-1">
    <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0" data-bs-toggle="collapse" data-bs-target="#prompt-category-<%= category.id %>-collapse" aria-expanded="false">
      <%= category.name %>
    </button>
    <div class="collapse" id="prompt-category-<%= category.id %>-collapse">
      <ul class="btn-toggle-nav list-unstyled small">
        <% prompts.each do |prompt| %>
          <li>
            <%= link_to prompt.title, prompt_path(prompt), class: 'link-body-emphasis text-decoration-none' %>
          </li>
        <% end %>
      </ul>
    </div>
  </li>
<% end %>

app/views/shared/_markdown.html.erb
<div class="form-container">
  <%= form_with model: object, url: url, method: method, local: true do |form| %>
    <% if object.is_a?(NoteForm) %>
      <%= form.hidden_field :prompt_id, value: prompt_id %>
    <% end %>
    <%= form.hidden_field :group_id, value: current_user.group_id %> 
    <%= form.label :category %>
    <div class="custom-field">
      <%= form.collection_select(:category_id, Category.all, :id, :name, {}, {class: 'form-control custom-select'}) %>
      <div class="toggle-group">
        <label>
          <%= form.check_box :is_public, { class: 'toggle-status', data: { on: 'Public', off: 'Private' } } %>
          <span class="toggle-label"
                data-on="Public"
                data-off="Private"
                data-state="<%= object&.public? ? 'on' : 'off' %>"></span>
        </label>
      </div>
      <div class="button-group">
        <%= form.submit 'Save', class: 'btn btn-success custom-btn' %>
      </div>
    </div>

    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control custom-input' %>

    <%= form.label :tags %>
    <%= form.text_field :tag_name, tag_name: "#{form.object_name}[name]", class: 'form-control custom-input-tag' %>
    <div id="search-result" class="list-group"></div>

    <%= form.label :content %>
    <%= form.text_area :content, id: 'markdown-editor', class: 'form-control' %>
  <% end %>
</div>

app/views/shared/_mypage_side_bar.html.erb
<% is_current_user = (current_user == @user) %>

<div class="profile-section text-center">
  <%= form_with(model: @user, url: user_path(@user), method: :patch, class: 'd-flex flex-column align-items-center') do |f| %>
    <% if @user.user_image.attached? %>
      <%= image_tag(@user.user_image, class: 'rounded-circle profile-img mb-3') %>
      <% if is_current_user %>
        <%= link_to 'Remove', user_path(@user), data: { turbo_method: :delete }, class: 'btn btn-danger' %>
      <% end %>
    <% else %>
      <% if is_current_user %>
        <div class="profile-icon rounded-circle mb-3">
          <label class="tooltip-container">
            <i class="bi bi-person-plus-fill mb-3"></i>
            <%= f.file_field :user_image, class: 'hidden' %>
            <span class="tooltip-text">写真を登録できます</span>
          </label>
        </div>
        <%= f.submit 'Update', class: 'btn btn-warning' %>
      <% else %>
        <div class="profile-icon rounded-circle mb-3">
          <label>
            <i class="bi bi-person-plus-fill mb-3"></i>
          </label>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>
<hr>
<div class="basic-section">
  <%= link_to '基本情報', basic_info_user_path(@user), class: 'sidebar-link', data: { target: 'basic_info' } %>
</div>
<hr>
<% if is_current_user %>
  <div class="notes-section">
    <%= link_to 'Note', notes_info_user_path(@user), class: 'sidebar-link', data: { target: 'notes_info' } %>
    <ul class="list-unstyled ps-0">
      <%= render partial: 'shared/category_note_list' %>
    </ul>
  </div>
  <hr>
  <div class="prompts-section">
    <%= link_to 'Prompt', prompts_info_user_path(@user), class: 'sidebar-link', data: { target: 'prompts_info' } %>
    <ul class="list-unstyled ps-0">
      <%= render partial: 'shared/category_prompt_list' %>
    </ul>
  </div>
<% end %>
<div class="mypage_sidebar-footer">
  <%= link_to 'Back', notes_path, class: 'btn btn-secondary' %>
</div>

app/views/shared/_note_boxes.html.erb
<div class="<%= "#{page}_note-box" %>">
  <div class="header">
    <div class="category"><%= object.category[:name] %></div>
    <div class="type" data-obj="<%= object&.is_a?(Note) ? 'Note' : 'Prompt' %>">
      <%= object.is_a?(Note) ? 'Note' : 'Prompt' %>
    </div>
  </div>
  <div class="tags">
    <% if object.tags.any? %>
      <% object.tags.each_with_index do |tag, index| %>
        <% if index < 5 %>
          <span class="tag tag-<%= tag.color_code %>"><%= tag.tag_name %></span>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="title"><%= object.title %></div>
  <div class="date"><%= object.days_since_last_update %>日前</div>
  <div class="footer">
    <%= link_to "Detail", dynamic_path(object, :show), class: 'btn details-button' %>
    <div class="informative"
          data-reference-id="<%= object.reference&.id %>"
          data-reference-type="<%= object.class.model_name.name %>"
          data-id="<%= object.id %>">
      <i class="bi bi-lightbulb icon-informative"></i>
      <span class="informative-count"><%= object.reference&.click_count || 0 %></span>
    </div>
  </div>
</div>

app/views/shared/_notes_box.html.erb
<div class="note-box">
  <div class="header">
    <div class="category"><%= object.category[:name] %></div>
    <div class="type" data-obj="<%= object&.is_a?(Note) ? 'Note' : 'Prompt' %>">
      <%= object.is_a?(Note) ? 'Note' : 'Prompt' %>
    </div>
  </div>
  <div class="tags">
    <% if object.tags.any? %>
      <% object.tags.each_with_index do |tag, index| %>
        <% if index < 5 %>
          <span class="tag tag-<%= tag.color_code %>"><%= tag.tag_name %></span>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="title"><%= object.title %></div>
  <div class="footer">
    <%= link_to "Detail", dynamic_path(object, :show), class: 'btn details-button' %>
    <div class="informative"
          data-reference-id="<%= object.reference&.id %>"
          data-reference-type="<%= object.class.model_name.name %>"
          data-id="<%= object.id %>">
      <i class="bi bi-lightbulb icon-informative"></i>
      <span class="informative-count"><%= object.reference&.click_count || 0 %></span>
    </div>
  </div>
</div>

app/views/shared/_notes_info.html.erb
<div class="note-info-section">
  <% if public_notes.any? %>
    <h3>Public Notes</h3>
    <div class="notes-list">
      <% public_notes.each do |note| %>
        <%= render partial: 'shared/note_boxes', locals: { object: note, page: 'mypage' } %>
      <% end %>
    </div>
  <% end %>

  <% if private_notes.any? %>
    <h3>Private Notes</h3>
    <div class="notes-list">
      <% private_notes.each do |note| %>
        <%= render partial: 'shared/note_boxes', locals: { object: note, page: 'mypage' } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_prompts_info.html.erb
<div class="prompt-info-section">
  <% if public_prompts.any? %>
    <h3>Public Prompts</h3>
    <div class="prompts-list">
      <% public_prompts.each do |prompt| %>
        <%= render partial: 'shared/note_boxes', locals: { object: prompt, page: 'mypage' } %>
      <% end %>
    </div>
  <% end %>

  <% if private_prompts.any? %>
    <h3>Private Prompts</h3>
    <div class="prompts-list">
      <% private_prompts.each do |prompt| %>
        <%= render partial: 'shared/note_boxes', locals: { object: prompt, page: 'mypage' } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_search_results.html.erb
<div class="search-filter-section">
  <%= form_with url: results_searches_path, method: :get, local: true do %>
    <div class="d-flex justify-content-center mb-3">
      <div class="input-group search-input-group">
        <%= text_field_tag :keyword, params[:keyword], placeholder: 'キーワード', class: 'form-control' %>
        <%= submit_tag 'Search', class: 'btn btn-primary' %>
      </div>
    </div>
    <div class="filter-section">
      <div class="form-group">
        <%= label_tag :sort, 'Sort' %>
        <%= select_tag :sort, options_for_select([['新しい順', 'created_desc'], ['古い順', 'created_asc'], ['参考数順', 'reference_count_desc']], params[:sort]), class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= label_tag :type, 'Type' %>
        <%= select_tag :type, options_for_select([['すべて', ''], ['Note', 'Note'], ['Prompt', 'Prompt']], params[:type]), class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= label_tag :category, 'Category' %>
        <%= select_tag :category, options_from_collection_for_select(Category.where.not(id: 1), :id, :name, params[:category]), include_blank: 'すべて', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= label_tag :tags, 'Tag' %>
        <%= select_tag :tags, options_from_collection_for_select(Tag.all, :id, :tag_name, params[:tags]), include_blank: 'すべて', class: 'form-control select2', multiple: true %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_show_markdown.html.erb
<div class="custom-field responsive-field">
  <h2><%= object.title %></h2>
  <div class="informative"
        data-reference-id="<%= object.reference&.id %>"
        data-reference-type="<%= object.class.model_name.name %>"
        data-id="<%= object.id %>">
    <i class="bi bi-lightbulb fs-5 icon-informative"></i>
    <span class="informative-count"><%= object.reference&.click_count || 0 %></span>
  </div>
  <div class="button-group">
    <% if object.is_a?(Prompt) %>
      <%= link_to 'NewNote from Prompt', new_prompt_note_path(object), class: 'btn btn-secondary custom-btn' %>
    <% end %>

    <% if user_signed_in? && object.user == current_user %>
      <%= link_to 'Edit', dynamic_path(object, :edit), class: 'btn btn-primary custom-btn' %>
      <%= link_to 'Delete', dynamic_path(object, :destroy), data: { turbo_method: :delete, turbo_confirm: '本当に削除してもよろしいですか?' }, class: 'btn btn-danger custom-btn' %>
    <% end %>
  </div>
</div>

<div>
  <strong>Category:</strong> <%= object.category.name %>
</div>
<div>
  <strong>Tags:</strong>
  <% if object.tags.any? %>
    <% object.tags.each do |tag| %>
      <span class="tag tag-<%= tag.color_code %>"><%= tag.tag_name %></span>
    <% end %>
  <% end %>
</div>
<div>
  <strong>Content</strong>
  <div class="markdown-preview"><%= markdown(object.content) %></div>
</div>
<div>
  <% if object.is_a?(Prompt) %>
    <% public_notes = @notes.select(&:public?) %>
    <% if public_notes.present? %>
      <strong>Example Answer</strong>
      <ul class="list-group small ps-4">
        <% public_notes.each do |note| %>
          <li><%= link_to note.title, note_path(note), class: 'link-body-emphasis text-decoration-none' %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>
<div class="author">
  <strong>Author:</strong> <%= link_to object.user.nickname, user_path(object.user), class: 'btn btn-outline-primary btn-sm author-link' %>
  <strong>Update:</strong> <%= object.days_since_last_update %>日前
</div>

app/views/shared/_side_bar.html.erb
<div class="side-bar-header">
  <ul class="tabs">
    <li><%= link_to 'Note', new_note_path, id: 'note-tab', class: "tab #{controller_name == 'notes' ? 'active' : ''}" %></li>
    <li><%= link_to 'Prompt', new_prompt_path, id: 'prompt-tab', class: "tab #{controller_name == 'prompts' ? 'active' : ''}" %></li>
  </ul>
</div>

<% if (context == :show || context == :edit) && user_signed_in? && current_user.id == object.user_id %>
  <div class="flex-shrink-0 p-3">
      <ul class="list-unstyled ps-0">
        <% if controller_name == 'notes' %>
          <%= render partial: 'shared/category_note_list' %>
        <% elsif controller_name == 'prompts' %>
          <%= render partial: 'shared/category_prompt_list' %>
        <% end %>
      </ul>
  </div>
<% end %>
<div class="sidebar-footer">
  <%= link_to 'Back', notes_path, class: 'btn btn-secondary' %>
</div>